services:
  server:
    build:
      context: .
      dockerfile: ./dist/docker/server/Dockerfile
    ports:
      - "8080:8080"
  client:
    build:
      context: .
      dockerfile: ./dist/docker/client/Dockerfile
    network_mode: host
    depends_on:
      - server
